import { Big_Shoulders_Inline_Text, Poppins, Roboto_Flex, Ubuntu } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const bigShouldersInlineText = Big_Shoulders_Inline_Text({ weight: ["300", "400", "500", "600", "700"], display: "swap", subsets: ["latin"], variable: "--font-big-shoulders-inline-text" });
const poppins = Poppins({ weight: ["300", "400", "500", "600", "700"], display: "swap", subsets: ["latin"], variable: "--font-poppins" });
const robotoFlex = Roboto_Flex({ weight: ["300", "400", "500", "700"], display: "swap", subsets: ["latin"], variable: "--font-roboto-flex" });
const ubuntu = Ubuntu({ weight: ["300", "400", "500", "700"], display: "swap", subsets: ["latin"], variable: "--font-ubuntu" });

export const metadata: Metadata = {
  title: "CSC PNJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bigShouldersInlineText.variable} ${poppins.variable} ${robotoFlex.variable} ${ubuntu.variable}`}>{children}</body>
    </html>
  );
}
